spring.application.name=prunusgym
# Conexión a la base de datos MySQL existente
spring.datasource.url=jdbc:mysql://localhost:3306/prunusgym
spring.datasource.username=root
spring.datasource.password=MYSQLPASSWORD
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de Hibernate/JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT
jwt.secret=T_7hOJyLGXxz0E7Zh4v5o5fOEFqib5XGxE0ASpJl5KhuC9aVjI4vLiHGuIngUHhZ
jwt.expiration-ms=28800000